// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Diagnostics() {
  return window['go']['main']['App']['Diagnostics']();
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetDomainStats() {
  return window['go']['main']['App']['GetDomainStats']();
}

export function GetLatency() {
  return window['go']['main']['App']['GetLatency']();
}

export function GetRemoteHealth() {
  return window['go']['main']['App']['GetRemoteHealth']();
}

export function GetRemoteVersion() {
  return window['go']['main']['App']['GetRemoteVersion']();
}

export function GetRouteRules() {
  return window['go']['main']['App']['GetRouteRules']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetTraffic() {
  return window['go']['main']['App']['GetTraffic']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function IsAutostartEnabled() {
  return window['go']['main']['App']['IsAutostartEnabled']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function LoadConfigFile(arg1) {
  return window['go']['main']['App']['LoadConfigFile'](arg1);
}

export function OpenExternalApp(arg1) {
  return window['go']['main']['App']['OpenExternalApp'](arg1);
}

export function ReloadVPN(arg1, arg2) {
  return window['go']['main']['App']['ReloadVPN'](arg1, arg2);
}

export function SelectServer(arg1) {
  return window['go']['main']['App']['SelectServer'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function StartVPN(arg1, arg2) {
  return window['go']['main']['App']['StartVPN'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopVPN() {
  return window['go']['main']['App']['StopVPN']();
}

export function ToggleRouteRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRouteRule'](arg1, arg2);
}
