// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CheckForUpdate():Promise<Record<string, any>>;

export function Diagnostics():Promise<core.DiagStatus>;

export function ExportConfig(arg1:string):Promise<string>;

export function GetDomainStats():Promise<Array<core.DomainScore>>;

export function GetLatency():Promise<number>;

export function GetRemoteHealth():Promise<Record<string, any>>;

export function GetRemoteVersion():Promise<Record<string, string>>;

export function GetRouteRules():Promise<Array<core.RouteRuleInfo>>;

export function GetServers():Promise<Array<core.ServerInfo>>;

export function GetTraffic():Promise<core.TrafficStats>;

export function ImportConfig(arg1:string):Promise<string>;

export function IsAutostartEnabled():Promise<boolean>;

export function ListConfigs():Promise<Array<string>>;

export function LoadConfigFile(arg1:string):Promise<string>;

export function OpenExternalApp(arg1:string):Promise<string>;

export function ReloadVPN(arg1:string,arg2:string):Promise<void>;

export function SelectServer(arg1:string):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function StartVPN(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<core.VPNStatus>;

export function StopVPN():Promise<void>;

export function ToggleRouteRule(arg1:number,arg2:boolean):Promise<void>;
